name: Dev Release

on:
  workflow_dispatch:

  push:
    branches: ["dev"]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: auto-deploy
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: "dev"
          destination_branch: "main"
          pr_title: "Staging ${{ github.ref }} into Main"
          pr_body: |
            :crown: *An automated PR*
            Pulling Dev branches into Main for release.
             - - -
              For Support, please visit the [Z90 Studios Site Issues](https://github.com/Z90-Studios/z90.studio/issues)
             - - -
              Preparing the stage.
          pr_label: "auto-pr"
